import './globals.css'

import type { Metadata } from "next";
import { Navbar } from "./components/common/navbar/Navbar";

export const metadata: Metadata = {
  title: "DevAI Writer",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="lemonade">
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
