export {default as Logo} from './Logo.svg'
export {default as ArrowBack} from './arrow-back.svg'
export {default as Eye} from './eye.svg'
export {default as EyeClosed} from './eye-closed.svg'
export {default as ToolTip} from './tooltips.svg'
export {default as LogoText} from './Logo-text.svg'